#! /bin/sh

# bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config borderless_monocle   false
bspc config focused_border_color "#b48ead"
bspc config normal_boarder_color "#2e3440"

bspc config window_gap            6
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# bspc rule -a firefox desktop=^2 follow=on
# bspc rule -a telegram-desktop desktop=^4 follow=on
