#! /bin/sh

#bspc monitor -d Home Web Work Files Mails Misc
bspc monitor -d I II III IV V VI

bspc config border_width         3
bspc config borderless_monocle   false
bspc config focused_border_color "#daa6ca"

bspc config window_gap            10
bspc config split_ratio           0.50
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

#bspc config normal_border_color "#353b45"

bspc rule -a librewolf desktop=^2 follow=on
bspc rule -a telegram-desktop desktop=^3 follow=on
